export const PATH_CREATE_STAFF = '/staff'
export const PATH_GET_STAFF_PAGINATION = '/staff/pagination'
export const PATH_CREATE_UPDATE_USER = '/user'
export const PATH_GET_USER_PAGINAtION = '/user/pagination'
export const PATH_CHANGE_USER_PASSWORD = '/user/change_password'
export const PATH_LOGIN = '/login'

export const PATH_REQUEST_RESET_PASSWORD = '/request_password_reset'
export const PATH_RESET_PASSWORD = '/reset_password'
export const PATH_CREATE_MENU_OPTION = '/menu_options'
export const PATH_GET_MENU_OPTION_WITH_PERMISSIONS =
  '/menu_options/get_with_permission'
export const PATH_GET_USER_MENU_OPTIONS = '/menu_options/:username'
export const PATH_GET_ROLE_PAGINATION = '/role/pagination'
export const PATH_CREATE_UPDATE_ROLE = '/role'
export const PATH_GET_ONE_ROLE = '/role/:roleId'
export const PATH_GET_PERMISSIONS_PAGINATION = '/permissions/pagination'
export const PATH_CREATE_UPDATE_PERSON = '/person'
export const PATH_GET_PERSON = '/person/:identifier'
export const PATH_GET_PERSON_PAGINATION = '/person/pagination'
export const PATH_CREATE_PERSON_REFERENCES = '/person/references'
export const PATH_UPDATE_PERSON_REFERENCE = '/person/reference'

export const PATH_CREATE_UPDATE_STUDENT = '/students'
export const PATH_GET_STUDENT = '/students/:id'
export const PATH_GET_STUDENT_PAGINATION = '/students/pagination'

export const PATH_CREATE_UPDATE_REQUEST = '/requests'
export const PATH_GET_REQUEST = '/requests/:id'
export const PATH_GET_REQUEST_PAGINATION = '/requests/pagination'

export const PATH_CREATE_UPDATE_CATALOG = '/catalogs'
export const PATH_GET_CATALOG_LIST = '/catalog/multi_list'
export const PATH_GET_CATALOG_PAGINATION = '/catalogs/pagination'
export const PATH_GET_CATALOG_ITEMS = '/catalogs/:key/items'
export const PATH_UPDATE_CATALOG_ITEM_BY_ID =
  '/catalogs/:catalogId/items/:itemId'
export const PATH_UPDATE_CATALOG_ITEM = '/catalog/item'
export const PATH_GET_CATALOG = '/catalog/:catalogId'

export const PATH_CREATE_UPDATE_PARAMETER = '/parameter'
export const PATH_GET_PARAMETER_PAGINATION = '/parameter/pagination'
export const PATH_GET_ACTIVITY_PARAMETER = '/parameter/:activityId'
