import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1764732461025 implements MigrationInterface {
    name = 'Migration1764732461025'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "PERSON" DROP CONSTRAINT "FK_PERSON_ROLE"`);
        await queryRunner.query(`ALTER TABLE "STUDENT" DROP CONSTRAINT "FK_STUDENT_PERSON"`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" DROP CONSTRAINT "FK_PARAMETER_MENU_OPTION"`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" DROP CONSTRAINT "FK_CATALOG_ITEM_CATALOG"`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" DROP CONSTRAINT "UQ_PARAMETER_MENU_OPTION"`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" DROP CONSTRAINT "UQ_CATALOG_ITEM_VALUE"`);
        await queryRunner.query(`CREATE TABLE "PASSWORD_RESET_TOKENS" ("ID" SERIAL NOT NULL, "TOKEN" character varying NOT NULL, "EXPIRES_AT" TIMESTAMP NOT NULL, "CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "USER_ID" integer, CONSTRAINT "PK_f2a4bd2d317f2efb4b62c53aedb" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`ALTER TABLE "REFERENCE" ADD "CREATED_AT" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "REFERENCE" ADD "CREATED_BY" integer`);
        await queryRunner.query(`ALTER TABLE "REFERENCE" ADD "STATE" character(1) NOT NULL DEFAULT 'A'`);
        await queryRunner.query(`ALTER TABLE "STUDENT" ALTER COLUMN "STATE" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" ALTER COLUMN "STATE" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" ALTER COLUMN "STATE" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CATALOG" ALTER COLUMN "STATE" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "PERSON" ADD CONSTRAINT "FK_f0fd6e27f9943244998c3346c4e" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE"("ROLE_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PASSWORD_RESET_TOKENS" ADD CONSTRAINT "FK_a0bd4aa2532b34b785edc6d0e71" FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_0f1c0ad9d07f4609f96c4e2330f" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON"("PERSON_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" ADD CONSTRAINT "FK_b7274355efca41defc57dbe6c1f" FOREIGN KEY ("MENU_OPTION_ID") REFERENCES "MENU_OPTION"("MENU_OPTION_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" ADD CONSTRAINT "FK_b58f5da01e8eab1c443b25e4418" FOREIGN KEY ("CATALOG_ID") REFERENCES "CATALOG"("CATALOG_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" DROP CONSTRAINT "FK_b58f5da01e8eab1c443b25e4418"`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" DROP CONSTRAINT "FK_b7274355efca41defc57dbe6c1f"`);
        await queryRunner.query(`ALTER TABLE "STUDENT" DROP CONSTRAINT "FK_0f1c0ad9d07f4609f96c4e2330f"`);
        await queryRunner.query(`ALTER TABLE "PASSWORD_RESET_TOKENS" DROP CONSTRAINT "FK_a0bd4aa2532b34b785edc6d0e71"`);
        await queryRunner.query(`ALTER TABLE "PERSON" DROP CONSTRAINT "FK_f0fd6e27f9943244998c3346c4e"`);
        await queryRunner.query(`ALTER TABLE "CATALOG" ALTER COLUMN "STATE" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" ALTER COLUMN "STATE" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" ALTER COLUMN "STATE" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "STUDENT" ALTER COLUMN "STATE" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "REFERENCE" DROP COLUMN "STATE"`);
        await queryRunner.query(`ALTER TABLE "REFERENCE" DROP COLUMN "CREATED_BY"`);
        await queryRunner.query(`ALTER TABLE "REFERENCE" DROP COLUMN "CREATED_AT"`);
        await queryRunner.query(`DROP TABLE "PASSWORD_RESET_TOKENS"`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" ADD CONSTRAINT "UQ_CATALOG_ITEM_VALUE" UNIQUE ("CATALOG_ID", "VALUE")`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" ADD CONSTRAINT "UQ_PARAMETER_MENU_OPTION" UNIQUE ("MENU_OPTION_ID", "PARAMETER")`);
        await queryRunner.query(`ALTER TABLE "CATALOG_ITEM" ADD CONSTRAINT "FK_CATALOG_ITEM_CATALOG" FOREIGN KEY ("CATALOG_ID") REFERENCES "CATALOG"("CATALOG_ID") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" ADD CONSTRAINT "FK_PARAMETER_MENU_OPTION" FOREIGN KEY ("MENU_OPTION_ID") REFERENCES "MENU_OPTION"("MENU_OPTION_ID") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_STUDENT_PERSON" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON"("PERSON_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PERSON" ADD CONSTRAINT "FK_PERSON_ROLE" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE"("ROLE_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
