BEGIN;

ALTER TABLE "SPONSOR"
ADD COLUMN IF NOT EXISTS "PERSON_ID" integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'FK_SPONSOR_PERSON'
  ) THEN
    ALTER TABLE "SPONSOR"
    ADD CONSTRAINT "FK_SPONSOR_PERSON"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("PERSON_ID")
    ON DELETE SET NULL ON UPDATE NO ACTION;
  END IF;
END $$;

ALTER TABLE "SPONSOR"
DROP COLUMN IF EXISTS "CONTACT_NAME",
DROP COLUMN IF EXISTS "CONTACT_EMAIL",
DROP COLUMN IF EXISTS "CONTACT_PHONE",
DROP COLUMN IF EXISTS "ADDRESS",
DROP COLUMN IF EXISTS "NOTES";

COMMIT;
